#spring.application.name=mspsystem
server.port=8080
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=majee.bikash1998@gmail.com
#spring.mail.password=Majeebikash#1998
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=root





spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# SMTP config (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=majee.bikash1998@gmail.com
spring.mail.password=tlnuqyvpzkrfzvxu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.main.allow-bean-definition-overriding=true
